"use client"

import { useMemo } from "react"
import { useCustomColors } from "@/lib/use-custom-colors"
import { useCurrency } from "@/contexts/currency-context"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/dashboard/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/dashboard/ui/tabs"
import { 
  BarChart3, 
  Calendar, 
  TrendingUp, 
  Trophy,
  Users,
  Zap
} from "lucide-react"
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  LabelList
} from "recharts"

import type { Event } from '@/types/dashboard/events/event'

interface EventAnalyticsProps {
  events: Event[]
}

export function EventAnalytics({ events }: EventAnalyticsProps) {
  const { primaryColor, secondaryColor } = useCustomColors()
  // Helper function to get event status
  function getEventStatus(startDate: string, endDate: string): "Upcoming" | "Ongoing" | "Completed" {
    const now = new Date()
    const start = new Date(startDate)
    const end = new Date(endDate)
    
    if (now < start) return "Upcoming"
    if (now > end) return "Completed"
    return "Ongoing"
  }

  const { currency } = useCurrency();

  // Statistics cards
  const topStats = useMemo(() => {
    const upcoming = events.filter(e => getEventStatus(e.startDate, e.endDate) === "Upcoming").length
    const ongoing = events.filter(e => getEventStatus(e.startDate, e.endDate) === "Ongoing").length
    const completed = events.filter(e => getEventStatus(e.startDate, e.endDate) === "Completed").length
    const totalParticipants = events.reduce((sum, e) => sum + e.participants, 0)
    const totalRevenue = events.reduce((sum, e) => sum + (e.revenue || 0), 0)
    
    return [
      { title: "Total Events", value: events.length, subtitle: "All events" },
      { title: "Total Revenue", value: `${currency} ${(totalRevenue / 100000).toFixed(1)}L`, subtitle: "Revenue generated" },
      { title: "Total Participants", value: totalParticipants, subtitle: "Across all events" },
      { title: "Ongoing Events", value: ongoing, subtitle: "Currently active" },
      { title: "Upcoming", value: upcoming, subtitle: "Not started" },
    ]
  }, [events])

  const statStyles = [
    { bg: "", titleText: "", valueText: "" },
    { bg: "bg-gradient-to-br from-green-50 to-green-100", titleText: "text-green-700", valueText: "text-green-900" },
    { bg: "bg-gradient-to-br from-blue-50 to-blue-100", titleText: "text-blue-700", valueText: "text-blue-900" },
    { bg: "bg-gradient-to-br from-amber-50 to-amber-100", titleText: "text-amber-700", valueText: "text-amber-900" },
    { bg: "", titleText: "", valueText: "" },
  ]

  // Revenue Generated by Event Chart
  const revenueChart = useMemo(() => {
    const revenue = new Map<string, number>()
    events.forEach(event => {
      const eventRevenue = event.revenue || 0
      revenue.set(event.name, (revenue.get(event.name) ?? 0) + eventRevenue)
    })
    return Array.from(revenue.entries())
      .map(([name, total]) => ({ name, revenue: total }))
      .sort((a, b) => b.revenue - a.revenue)
  }, [events])

  // Events by Type Chart - REMOVED
  // const typeChart = useMemo(() => {
  //   const types = new Map<string, number>()
  //   events.forEach(event => {
  //     types.set(event.type, (types.get(event.type) ?? 0) + 1)
  //   })
  //   return Array.from(types.entries())
  //     .map(([type, count]) => ({ type, events: count }))
  //     .sort((a, b) => b.events - a.events)
  // }, [events])

  // Events by Skill Level Chart
  const skillLevelChart = useMemo(() => {
    const levels = new Map<string, number>()
    events.forEach(event => {
      levels.set(event.skillLevel, (levels.get(event.skillLevel) ?? 0) + 1)
    })
    const order = ["Beginner", "Intermediate", "Advanced", "All Levels"]
    return Array.from(levels.entries())
      .map(([level, count]) => ({ level, events: count }))
      .sort((a, b) => order.indexOf(a.level) - order.indexOf(b.level))
  }, [events])

  // Events by Status Chart
  const statusChart = useMemo(() => {
    const upcoming = events.filter(e => getEventStatus(e.startDate, e.endDate) === "Upcoming").length
    const ongoing = events.filter(e => getEventStatus(e.startDate, e.endDate) === "Ongoing").length
    const completed = events.filter(e => getEventStatus(e.startDate, e.endDate) === "Completed").length
    
    return [
      { status: "Upcoming", events: upcoming },
      { status: "Ongoing", events: ongoing },
      { status: "Completed", events: completed },
    ]
  }, [events])

  // Monthly Events Chart
  const monthlyChart = useMemo(() => {
    const now = new Date()
    const sixMonthsAgo = new Date(now.getFullYear(), now.getMonth() - 5, 1)
    const sixMonthsAgoKey = `${sixMonthsAgo.getFullYear()}-${String(sixMonthsAgo.getMonth() + 1).padStart(2, '0')}`
    
    const monthCounts = new Map<string, number>()
    events.forEach(event => {
      const date = new Date(event.startDate)
      if (!isNaN(date.getTime())) {
        const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
        if (key >= sixMonthsAgoKey) {
          monthCounts.set(key, (monthCounts.get(key) ?? 0) + 1)
        }
      }
    })
    
    const allMonths = new Map<string, number>()
    for (let i = 5; i >= 0; i--) {
      const date = new Date(now.getFullYear(), now.getMonth() - i, 1)
      const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
      allMonths.set(key, monthCounts.get(key) ?? 0)
    }
    
    const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    return Array.from(allMonths.entries()).map(([key, count]) => {
      const [year, month] = key.split("-")
      const monthIndex = parseInt(month) - 1
      return {
        month: `${monthNames[monthIndex]} '${year.slice(2)}`,
        events: count,
      }
    })
  }, [events])

  // Events by Staff Chart
  const staffChart = useMemo(() => {
    const staffMembers = new Map<string, number>()
    events.forEach(event => {
      staffMembers.set(event.staff, (staffMembers.get(event.staff) ?? 0) + 1)
    })
    return Array.from(staffMembers.entries())
      .map(([staff, count]) => ({ staff, events: count }))
      .sort((a, b) => b.events - a.events)
  }, [events])

  // Events by Sport Chart
  const sportChart = useMemo(() => {
    const sports = new Map<string, number>()
    events.forEach(event => {
      sports.set(event.sport, (sports.get(event.sport) ?? 0) + 1)
    })
    return Array.from(sports.entries())
      .map(([sport, count]) => ({ sport, events: count }))
      .sort((a, b) => b.events - a.events)
  }, [events])

  // Format Chart
  const formatChart = useMemo(() => {
    const formats = new Map<string, number>()
    events.forEach(event => {
      formats.set(event.format, (formats.get(event.format) ?? 0) + 1)
    })
    return Array.from(formats.entries())
      .map(([format, count]) => ({ format, events: count }))
  }, [events])

  const COLORS = ['#8A2BE2', '#FF7F50', '#228B22', '#FF6347', '#4169E1', '#FFD700', '#20B2AA', '#FF1493']

  return (
    <div className="w-full space-y-4">
      <div className="sticky top-0 z-20 bg-background dark:bg-gray-900 pt-4 pb-4">
        {/* Top Statistics */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        {topStats.map((stat, index) => {
          const isThemed = index === 0 || index === 4
          return (
            <Card
              key={index}
              className={`${isThemed ? '' : statStyles[index]?.bg} border shadow-sm`}
              style={isThemed ? { backgroundImage: `linear-gradient(135deg, ${primaryColor}15, ${secondaryColor}26)` } : {}}
            >
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className={`text-sm font-medium ${isThemed ? '' : statStyles[index]?.titleText}`} style={isThemed ? { color: primaryColor } : {}}>{stat.title}</p>
                    <p className={`text-2xl font-bold ${isThemed ? '' : statStyles[index]?.valueText}`} style={isThemed ? { color: primaryColor } : {}}>{stat.value}</p>
                    <p className={`text-xs ${isThemed ? '' : statStyles[index]?.titleText} opacity-80`} style={isThemed ? { color: primaryColor } : {}}>{stat.subtitle}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          )
        })}
        </div>
      </div>

      {/* Charts */}
      <Tabs defaultValue="overview" className="space-y-4">
        <TabsList className="grid w-full grid-cols-3 bg-transparent p-0 h-auto gap-2">
          <TabsTrigger 
            value="overview"
            className="bg-background dark:bg-gray-900 border-2 rounded-lg transition-all duration-150 font-semibold px-5 py-2 data-[state=active]:text-white data-[state=active]:bg-gradient-to-r data-[state=active]:from-[var(--pc)] data-[state=active]:to-[var(--sc)] data-[state=active]:border-[var(--pc)] hover:text-white hover:bg-gradient-to-r hover:from-[var(--pc)] hover:to-[var(--sc)] hover:border-[var(--pc)] focus:outline-none shadow-sm"
            style={{
              // @ts-ignore
              ['--pc']: primaryColor,
              ['--sc']: secondaryColor,
              color: secondaryColor,
              borderColor: secondaryColor,
            }}
          >
            Distribution & Revenue
          </TabsTrigger>
          <TabsTrigger 
            value="details"
            className="bg-background dark:bg-gray-900 border-2 rounded-lg transition-all duration-150 font-semibold px-5 py-2 data-[state=active]:text-white data-[state=active]:bg-gradient-to-r data-[state=active]:from-[var(--pc)] data-[state=active]:to-[var(--sc)] data-[state=active]:border-[var(--pc)] hover:text-white hover:bg-gradient-to-r hover:from-[var(--pc)] hover:to-[var(--sc)] hover:border-[var(--pc)] focus:outline-none shadow-sm"
            style={{
              // @ts-ignore
              ['--pc']: primaryColor,
              ['--sc']: secondaryColor,
              color: secondaryColor,
              borderColor: secondaryColor,
            }}
          >
            Details & Breakdown
          </TabsTrigger>
          <TabsTrigger 
            value="trends"
            className="bg-background dark:bg-gray-900 border-2 rounded-lg transition-all duration-150 font-semibold px-5 py-2 data-[state=active]:text-white data-[state=active]:bg-gradient-to-r data-[state=active]:from-[var(--pc)] data-[state=active]:to-[var(--sc)] data-[state=active]:border-[var(--pc)] hover:text-white hover:bg-gradient-to-r hover:from-[var(--pc)] hover:to-[var(--sc)] hover:border-[var(--pc)] focus:outline-none shadow-sm"
            style={{
              // @ts-ignore
              ['--pc']: primaryColor,
              ['--sc']: secondaryColor,
              color: secondaryColor,
              borderColor: secondaryColor,
            }}
          >
            Trends & Timeline
          </TabsTrigger>
        </TabsList>

        {/* Overview Tab */}
        <TabsContent value="overview" className="space-y-4">
          {/* Revenue Generated by Event - Big Card */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2" style={{ color: primaryColor }}>
                <TrendingUp className="h-4 w-4" style={{ color: primaryColor }} />
                Revenue Generated by Event
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-[400px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart 
                    data={revenueChart}
                    margin={{ top: 25, right: 10, left: 10, bottom: 80 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis 
                      dataKey="name" 
                      label={{ value: 'Events', position: 'insideBottom', offset: -15 }}
                      angle={-45}
                      textAnchor="end"
                      height={80}
                      style={{ fontSize: '11px' }}
                    />
                    <YAxis 
                      label={{ value: 'Revenue ($)', angle: -90, position: 'insideLeft', offset: 0 }}
                      allowDecimals={false}
                    />
                    <Tooltip formatter={(value: any) => [`$${value.toLocaleString()}`, 'revenue']} />
                    <Bar dataKey="revenue" fill="url(#revenueGradient)">
                      <LabelList dataKey="revenue" position="top" offset={5} formatter={(value: any) => `$${(value / 1000).toFixed(1)}k`} />
                    </Bar>
                    <defs>
                      <linearGradient id="revenueGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor={primaryColor} />
                        <stop offset="100%" stopColor={secondaryColor} />
                      </linearGradient>
                    </defs>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Details Tab */}
        <TabsContent value="details" className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            {/* Events by Sport */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base" style={{ color: primaryColor }}>
                  <BarChart3 className="h-4 w-4" style={{ color: primaryColor }} />
                  Events by Sport
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-[340px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart 
                      data={sportChart}
                      margin={{ top: 25, right: 10, left: 10, bottom: 80 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis 
                        dataKey="sport" 
                        label={{ value: 'Sports', position: 'insideBottom', offset: -15 }}
                        angle={-45}
                        textAnchor="end"
                        height={80}
                        style={{ fontSize: '11px' }}
                      />
                      <YAxis 
                        label={{ value: 'Events', angle: -90, position: 'insideLeft', offset: 0 }}
                        allowDecimals={false}
                      />
                      <Tooltip formatter={(value: any) => [String(value), 'events']} />
                      <Bar dataKey="events" fill="url(#sportGradient)">
                        <LabelList dataKey="events" position="top" offset={5} />
                      </Bar>
                      <defs>
                        <linearGradient id="sportGradient" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor={primaryColor} />
                          <stop offset="100%" stopColor={secondaryColor} />
                        </linearGradient>
                      </defs>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>

            {/* Events by Skill Level */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base" style={{ color: primaryColor }}>
                  <Users className="h-4 w-4" style={{ color: primaryColor }} />
                  Events by Skill Level
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-[340px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart 
                      data={skillLevelChart}
                      margin={{ top: 25, right: 10, left: 10, bottom: 80 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis 
                        dataKey="level" 
                        label={{ value: 'Skill Level', position: 'insideBottom', offset: -15 }}
                        angle={-45}
                        textAnchor="end"
                        height={80}
                        style={{ fontSize: '11px' }}
                      />
                      <YAxis 
                        label={{ value: 'Events', angle: -90, position: 'insideLeft', offset: 0 }}
                        allowDecimals={false}
                      />
                      <Tooltip formatter={(value: any) => [String(value), 'events']} />
                      <Bar dataKey="events" fill="url(#skillGradient)">
                        <LabelList dataKey="events" position="top" offset={5} />
                      </Bar>
                      <defs>
                        <linearGradient id="skillGradient" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor={primaryColor} />
                          <stop offset="100%" stopColor={secondaryColor} />
                        </linearGradient>
                      </defs>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>

            {/* Events by Staff */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base" style={{ color: primaryColor }}>
                  <Users className="h-4 w-4" style={{ color: primaryColor }} />
                  Events by Staff
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-[340px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart 
                      data={staffChart}
                      margin={{ top: 25, right: 10, left: 10, bottom: 80 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis 
                        dataKey="staff" 
                        label={{ value: 'Staff', position: 'insideBottom', offset: -15 }}
                        angle={-45}
                        textAnchor="end"
                        height={80}
                        style={{ fontSize: '11px' }}
                      />
                      <YAxis 
                        label={{ value: 'Events', angle: -90, position: 'insideLeft', offset: 0 }}
                        allowDecimals={false}
                      />
                      <Tooltip formatter={(value: any) => [String(value), 'events']} />
                      <Bar dataKey="events" fill="url(#staffGradient)">
                        <LabelList dataKey="events" position="top" offset={5} />
                      </Bar>
                      <defs>
                        <linearGradient id="staffGradient" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor={primaryColor} />
                          <stop offset="100%" stopColor={secondaryColor} />
                        </linearGradient>
                      </defs>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>

            {/* Events by Format */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base" style={{ color: primaryColor }}>
                  <Zap className="h-4 w-4" style={{ color: primaryColor }} />
                  Events by Format
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-[340px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart 
                      data={formatChart}
                      margin={{ top: 25, right: 10, left: 10, bottom: 10 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis 
                        dataKey="format" 
                        label={{ value: 'Format', position: 'insideBottom', offset: 0 }}
                        angle={0}
                        textAnchor="middle"
                        height={60}
                        style={{ fontSize: '11px' }}
                      />
                      <YAxis 
                        label={{ value: 'Events', angle: -90, position: 'insideLeft', offset: 0 }}
                        allowDecimals={false}
                      />
                      <Tooltip formatter={(value: any) => [String(value), 'events']} />
                      <Bar dataKey="events" fill="url(#formatGradient)">
                        <LabelList dataKey="events" position="top" offset={5} />
                      </Bar>
                      <defs>
                        <linearGradient id="formatGradient" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor={primaryColor} />
                          <stop offset="100%" stopColor={secondaryColor} />
                        </linearGradient>
                      </defs>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Trends Tab */}
        <TabsContent value="trends" className="space-y-4">
          {/* Events Timeline */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2" style={{ color: primaryColor }}>
                <Calendar className="h-4 w-4" style={{ color: primaryColor }} />
                Events Timeline (Last 6 Months)
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-[340px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart
                    data={monthlyChart}
                    margin={{ top: 25, right: 10, left: 10, bottom: 80 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis 
                      dataKey="month" 
                      label={{ value: 'Month', position: 'insideBottom', offset: -15 }}
                      angle={-45}
                      textAnchor="end"
                      height={80}
                      style={{ fontSize: '11px' }}
                    />
                    <YAxis 
                      label={{ value: 'Events', angle: -90, position: 'insideLeft', offset: 0 }}
                      allowDecimals={false}
                    />
                    <Tooltip formatter={(value: any) => [String(value), 'events']} />
                    <Bar dataKey="events" fill="url(#trendGradient)">
                      <LabelList dataKey="events" position="top" offset={5} />
                    </Bar>
                    <defs>
                      <linearGradient id="trendGradient" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor={primaryColor} />
                        <stop offset="100%" stopColor={secondaryColor} />
                      </linearGradient>
                    </defs>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
