// Comprehensive (trimmed) list of phone country codes for dropdown usage.
// Each entry: dialing code (E.164), country name, optional ISO2 for future flag support.
export interface PhoneCountryCode { code: string; country: string; iso2?: string }

export const PHONE_COUNTRY_CODES: PhoneCountryCode[] = [
  { code: '+1', country: 'United States / Canada', iso2: 'US' },
  { code: '+7', country: 'Russia', iso2: 'RU' },
  { code: '+20', country: 'Egypt', iso2: 'EG' },
  { code: '+27', country: 'South Africa', iso2: 'ZA' },
  { code: '+30', country: 'Greece', iso2: 'GR' },
  { code: '+31', country: 'Netherlands', iso2: 'NL' },
  { code: '+32', country: 'Belgium', iso2: 'BE' },
  { code: '+33', country: 'France', iso2: 'FR' },
  { code: '+34', country: 'Spain', iso2: 'ES' },
  { code: '+36', country: 'Hungary', iso2: 'HU' },
  { code: '+39', country: 'Italy', iso2: 'IT' },
  { code: '+40', country: 'Romania', iso2: 'RO' },
  { code: '+41', country: 'Switzerland', iso2: 'CH' },
  { code: '+43', country: 'Austria', iso2: 'AT' },
  { code: '+44', country: 'United Kingdom', iso2: 'GB' },
  { code: '+45', country: 'Denmark', iso2: 'DK' },
  { code: '+46', country: 'Sweden', iso2: 'SE' },
  { code: '+47', country: 'Norway', iso2: 'NO' },
  { code: '+48', country: 'Poland', iso2: 'PL' },
  { code: '+49', country: 'Germany', iso2: 'DE' },
  { code: '+52', country: 'Mexico', iso2: 'MX' },
  { code: '+54', country: 'Argentina', iso2: 'AR' },
  { code: '+55', country: 'Brazil', iso2: 'BR' },
  { code: '+60', country: 'Malaysia', iso2: 'MY' },
  { code: '+61', country: 'Australia', iso2: 'AU' },
  { code: '+62', country: 'Indonesia', iso2: 'ID' },
  { code: '+63', country: 'Philippines', iso2: 'PH' },
  { code: '+64', country: 'New Zealand', iso2: 'NZ' },
  { code: '+65', country: 'Singapore', iso2: 'SG' },
  { code: '+66', country: 'Thailand', iso2: 'TH' },
  { code: '+81', country: 'Japan', iso2: 'JP' },
  { code: '+82', country: 'South Korea', iso2: 'KR' },
  { code: '+84', country: 'Vietnam', iso2: 'VN' },
  { code: '+86', country: 'China', iso2: 'CN' },
  { code: '+90', country: 'Turkey', iso2: 'TR' },
  { code: '+91', country: 'India', iso2: 'IN' },
  { code: '+92', country: 'Pakistan', iso2: 'PK' },
  { code: '+93', country: 'Afghanistan', iso2: 'AF' },
  { code: '+94', country: 'Sri Lanka', iso2: 'LK' },
  { code: '+95', country: 'Myanmar', iso2: 'MM' },
  { code: '+98', country: 'Iran', iso2: 'IR' },
  { code: '+234', country: 'Nigeria', iso2: 'NG' },
  { code: '+254', country: 'Kenya', iso2: 'KE' },
  { code: '+351', country: 'Portugal', iso2: 'PT' },
  { code: '+352', country: 'Luxembourg', iso2: 'LU' },
  { code: '+353', country: 'Ireland', iso2: 'IE' },
  { code: '+354', country: 'Iceland', iso2: 'IS' },
  { code: '+355', country: 'Albania', iso2: 'AL' },
  { code: '+356', country: 'Malta', iso2: 'MT' },
  { code: '+357', country: 'Cyprus', iso2: 'CY' },
  { code: '+358', country: 'Finland', iso2: 'FI' },
  { code: '+359', country: 'Bulgaria', iso2: 'BG' },
  { code: '+370', country: 'Lithuania', iso2: 'LT' },
  { code: '+371', country: 'Latvia', iso2: 'LV' },
  { code: '+372', country: 'Estonia', iso2: 'EE' },
  { code: '+373', country: 'Moldova', iso2: 'MD' },
  { code: '+374', country: 'Armenia', iso2: 'AM' },
  { code: '+375', country: 'Belarus', iso2: 'BY' },
  { code: '+376', country: 'Andorra', iso2: 'AD' },
  { code: '+377', country: 'Monaco', iso2: 'MC' },
  { code: '+380', country: 'Ukraine', iso2: 'UA' },
  { code: '+381', country: 'Serbia', iso2: 'RS' },
  { code: '+382', country: 'Montenegro', iso2: 'ME' },
  { code: '+385', country: 'Croatia', iso2: 'HR' },
  { code: '+386', country: 'Slovenia', iso2: 'SI' },
  { code: '+387', country: 'Bosnia and Herzegovina', iso2: 'BA' },
  { code: '+389', country: 'North Macedonia', iso2: 'MK' },
  { code: '+420', country: 'Czech Republic', iso2: 'CZ' },
  { code: '+421', country: 'Slovakia', iso2: 'SK' },
  { code: '+423', country: 'Liechtenstein', iso2: 'LI' },
  { code: '+880', country: 'Bangladesh', iso2: 'BD' },
  { code: '+960', country: 'Maldives', iso2: 'MV' },
  { code: '+961', country: 'Lebanon', iso2: 'LB' },
  { code: '+962', country: 'Jordan', iso2: 'JO' },
  { code: '+963', country: 'Syria', iso2: 'SY' },
  { code: '+964', country: 'Iraq', iso2: 'IQ' },
  { code: '+965', country: 'Kuwait', iso2: 'KW' },
  { code: '+966', country: 'Saudi Arabia', iso2: 'SA' },
  { code: '+967', country: 'Yemen', iso2: 'YE' },
  { code: '+968', country: 'Oman', iso2: 'OM' },
  { code: '+971', country: 'United Arab Emirates', iso2: 'AE' },
  { code: '+972', country: 'Israel', iso2: 'IL' },
  { code: '+973', country: 'Bahrain', iso2: 'BH' },
  { code: '+974', country: 'Qatar', iso2: 'QA' },
  { code: '+975', country: 'Bhutan', iso2: 'BT' },
  { code: '+976', country: 'Mongolia', iso2: 'MN' },
  { code: '+977', country: 'Nepal', iso2: 'NP' },
  { code: '+992', country: 'Tajikistan', iso2: 'TJ' },
  { code: '+993', country: 'Turkmenistan', iso2: 'TM' },
  { code: '+994', country: 'Azerbaijan', iso2: 'AZ' },
  { code: '+995', country: 'Georgia', iso2: 'GE' },
  { code: '+996', country: 'Kyrgyzstan', iso2: 'KG' },
  { code: '+998', country: 'Uzbekistan', iso2: 'UZ' },
];

// Provide a quick lookup (map) if needed later.
export const PHONE_COUNTRY_CODE_MAP = new Map(PHONE_COUNTRY_CODES.map(c => [c.code, c]));
