export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Nested layouts must not render additional <html> or <body> tags.
  // Return children directly so the root layout's html/body attributes remain consistent.
  return <>{children}</>
}
