export type Parent = {
  id?: string;
  parentId: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  email: string;
  mobile: string;
  countryCode: string;
  country: string;
  dob?: string | Date;
  linkedStudentId: string;
  categories: string[];
  paymentStatus: 'Paid' | 'Pending' | 'Overdue';
  totalFees: number;
  amountPaid: number;
  dueAmount: number;
  currency: string;
  lastPaymentDate?: string | Date;
  verificationStatus: 'Verified' | 'Pending' | 'Rejected';
  status: 'Active' | 'Inactive';
  joinDate: string | Date;
  lastLogin?: string | Date;
  address: string;
  city: string;
  stateProvince: string;
  pincode: string;
  engagementScore: number;
  isDeleted?: boolean;
  deletedAt?: string | Date;
  createdAt?: string | Date;
  updatedAt?: string | Date;
};
